"""Build ATT&CK coverage from shipped rules plus the planned backlog.

Outputs:
  coverage/attack-layer.json  -> load in ATT&CK Navigator (Open Existing Layer)
  coverage/COVERAGE.md        -> table rendered on GitHub
"""
import json
from collections import defaultdict

import yaml

from common import ROOT, load_rules

attack_data = json.loads((ROOT / "data" / "attack_index.json").read_text())
attack = attack_data["techniques"]
planned = yaml.safe_load((ROOT / "roadmap.yml").read_text())["planned"]

STATUS_SCORE = {"stable": 100, "testing": 75, "experimental": 60, "planned": 20}
cells = defaultdict(list)  # (technique, tactic) -> [(status, id, title)]

for _, meta in load_rules():
    for m in meta["attack"]:
        cells[(m["technique"], m["tactic"])].append((meta["status"], meta["id"], meta["title"]))
for p in planned:
    for m in p["attack"]:
        cells[(m["technique"], m["tactic"])].append(("planned", "planned", p["title"]))

techniques = []
for (tid, tactic), items in sorted(cells.items()):
    score = max(STATUS_SCORE[s] for s, _, _ in items)
    techniques.append({
        "techniqueID": tid,
        "tactic": tactic,
        "score": score,
        "comment": "; ".join(f"{i} {t} ({s})" for s, i, t in items),
        "enabled": True,
        "showSubtechniques": "." in tid,
    })

layer = {
    "name": "Identity Threat Detections: coverage",
    "versions": {"layer": "4.5", "navigator": "5.1.0", "attack": "18"},
    "domain": "enterprise-attack",
    "description": "Green = shipped and tested. Pale = planned. Generated by tools/coverage.py.",
    "techniques": techniques,
    "gradient": {"colors": ["#f3f5f6", "#9fd3b0", "#1f7a4d"], "minValue": 0, "maxValue": 100},
    "legendItems": [
        {"label": "Shipped and tested", "color": "#1f7a4d"},
        {"label": "Planned", "color": "#dcefe2"},
    ],
    "hideDisabled": False,
}
out = ROOT / "coverage"
out.mkdir(exist_ok=True)
(out / "attack-layer.json").write_text(json.dumps(layer, indent=2))

lines = ["# ATT&CK coverage", "",
         "Generated by `tools/coverage.py`. Load `attack-layer.json` in the "
         "[ATT&CK Navigator](https://mitre-attack.github.io/attack-navigator/) for the heatmap.", "",
         "| Technique | Tactic | Detections |", "|---|---|---|"]
for (tid, tactic), items in sorted(cells.items()):
    name = attack[tid]["name"]
    det = "<br>".join(f"{'`'+i+'`' if i != 'planned' else 'planned:'} {t} ({s})" if i != "planned" else f"planned: {t}" for s, i, t in items)
    lines.append(f"| {tid} {name} | {tactic} | {det} |")
shipped = sum(1 for items in cells.values() if any(s != "planned" for s, _, _ in items))
lines += ["", f"{shipped} technique/tactic pairs covered by tested rules, {len(cells) - shipped} planned."]
(out / "COVERAGE.md").write_text("\n".join(lines) + "\n")
print(f"coverage: {shipped} covered, {len(cells) - shipped} planned")
